[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"
# requires = ["setuptools >= 77.0.3"]
# build-backend = "setuptools.build_meta"

# define basic package information
[project]
name = "QBitBridge"
dynamic = ["version"]
description = "Hybrid workflow framework for running (v)QPUs, GPUs and CPUs"
authors = [
    {name = "pelahi", email = "pascal.elahi@pawsey.org.au"},
]
maintainers = [
    {name = "pelahi", email = "pascal.elahi@pawsey.org.au"},
]
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["quantum computing", "supercomputing", "hybrid", "workflow"]
readme = "README.md"
# include = [
#     {path = 'qbitbridge'},
#     {path = 'workflow/clusters'},
#     {path = 'workflow/scripts/'},
#     {path = 'workflow/tests/'},
# ]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Scientific/Engineering :: Quantum Computing",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Software Development :: Libraries",
  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.11"
# set dependencies
dependencies = [
    "prefect",
    "prefect-dask",
    "dask-jobqueue",
    "numpy",
    "pydantic",
    "scipy",
    "spython",
    "matplotlib",
    # "sckikit-image",
]

[tool.hatch.version]
path = "qbitbridge/__about__.py"


[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["qbitbridge"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
combine_as_imports = true
multi_line_output = 3
length_sort = true
src_paths = ["qbitbridge"]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py311"
lint.ignore = ["F401", "E401", "E402", "F841", "E741"]
lint.extend-select = ["F541", "E711"]
indent-width = 4

[project.urls]
Documentation = "https://pawseysc.github.io/vqpu-hybrid-workflow/"
Repository = "https://github.com/PawseySC/vqpu-hybrid-workflow.git"
Issues = "https://github.com/PawseySC/vqpu-hybrid-workflow/issues"
Changelog = "https://github.com/PawseySC/vqpu-hybrid-workflow/blob/master/CHANGELOG.md"


[project.optional-dependencies]
docs = ["sphinx"]
test = [
  "pytest",
  "pytest-cov",
]
dev = [
    "black",
    "mypy",
    "isort",
    "pre-commit",
    "ruff",
    "pytest",
    "pytest-cov",
    "sphinx",
]
fitting = [
    "emcee",
    "corner",
    "pandas",
    "dynesty",
    "h5py",
]
quera = [
    "bloqade",
    "bloqade-analogue",
]
qiskit = [
    "qiskit",
    "qiskit_ibm_runtime",
    "qiskit_aer"
]
braket = [
    "awscli",
    "amazon-braket-sdk",
]
cudaq = [
    "cudaq",
]
